добавлена валидация
htmlacademy-javascript/1895687-keksobooking-25 pull request #7
Opened 2022-03-17 03:46 UTC by Stanizlav

2022-03-18 07:06 UTC, Dima-Dim requested changes
https://htmlacademy-javascript.github.io/1895687-keksobooking-25/7/
сейчас при заходе на страницу сразу видны сообщения об ошибках в заполнении полей формы. Но форму никто не трогал. Это не очень дружелюбное поведение валидации.

2022-03-18 07:06 UTC, Dima-Dim commented on js/user-form.js
> +fieldsCollection.forEach((field)=>{
Такие конструкции лучше оборачивать в функции, в которые передаются значения, от которых они зависят.

2022-03-18 07:06 UTC, Dima-Dim commented on js/user-form.js
> +const validatePrice = (value)=>(value>=minPrice[accomodation.value]);
Не нужно экономить на пробелах и писать не читаемый код.

2022-03-19 04:36 UTC, Dima-Dim commented on js/user-form.js
> +const validateCapacity = (value) => +rooms.value === 100 && +value === 0 ||
Магические цифры.

2022-03-19 04:36 UTC, Dima-Dim commented on js/user-form.js
> +  if(+capacity.value > +rooms.value){
Лучше использовать явное приведение типов, в данном случае, например, через Number.

2022-03-19 04:36 UTC, merged

2022-03-19 10:47 UTC, Stanizlav commented on js/user-form.js
> +  if(+capacity.value > +rooms.value){
Сначала хотел привести явно (Number()), но неявное приведение, по моему мнению, дало бОльшую наглядность, поэтому привёл неявно

2022-03-19 10:48 UTC, Stanizlav commented on js/user-form.js
> +const validateCapacity = (value) => +rooms.value === 100 && +value === 0 ||
Понял - принял - исправлю)

2022-03-20 05:43 UTC, Dima-Dim commented on js/user-form.js
> +  if(+capacity.value > +rooms.value){
Как оно может давать большую наглядность, если у этого знака как минимум 3 варианта использование? Сложение, конкатенация и побочное действие от сложения - приведения к числу. Видя же Number не нужно задумываться что здесь происходит, сразу понятно что тут нам нужно число, а в переменной может и не число, вот мы и приводим его к числу.