Были добавлены карта и слайдер
htmlacademy-javascript/1895687-keksobooking-25 pull request #9
Opened 2022-03-22 00:43 UTC by Stanizlav

2022-03-22 07:15 UTC, Dima-Dim requested changes
Убрать избыточные приведения типов.

2022-03-22 07:15 UTC, Dima-Dim commented on js/create-location.js
> +  const ACCURACY = 7;             //digits after the decimal point
Как только возникает желание написать такой комментарий, стоит задуматься над названием такой переменной.

2022-03-22 07:15 UTC, Dima-Dim commented on js/user-ad-form.js
> +      return Number(value.toFixed(0));
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed
Там и так число на выходе, зачем его приводить к числу? Не нужно делать избыточных проверок и операций.

2022-03-22 07:15 UTC, Dima-Dim commented on js/user-map.js
> +const zoomLevel = 15;
https://up.htmlacademy.ru/javascript/25/criteries#b7

2022-03-22 07:15 UTC, Dima-Dim commented on js/user-map.js
> +  const lat = +location.lat.toFixed(7);
Тоже приведение числа к числу, ещё и не явное.

2022-03-22 12:07 UTC, Stanizlav commented on js/user-ad-form.js
> +      return Number(value.toFixed(0));
Согласен, что приведение излишнее, но toFixed() возвращает строку, вот я на автомате к числу и приводил, хотя всё равно даже в поле с типом "number" значение имеет строковый тип

2022-03-23 06:58 UTC, Dima-Dim commented on js/user-map.js
> +  iconUrl:    '../img/main-pin.svg',
https://htmlacademy-javascript.github.io/1895687-keksobooking-25/9/ - балуны не отображаются. Когда будешь делать следующее задание, обрати на это внимание.

2022-03-23 06:58 UTC, merged